# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_DEV_URL'] %>
test:
  url: <%= ENV['SOLR_DEV_URL'] %>
production:
  url: <%= ENV['SOLR_PROD_URL'] %>

