# test setup for testing production setup
# locally.

version: '3.7'

services:
  hydra:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    container_name: %%project_name%%
    restart: always    
    environment:
      - SECRET_KEY_BASE=%%secret_key_base%%
      - FEDORA_PROD_URL=http://fcrepo:8080/rest/
      - FEDORA_PASSWORD=fedoraAdmin
      - SOLR_PROD_URL=http://solr:8983/solr/hydra_prod/
      - MYSQL_PASSWORD="changeme"
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - TERM=xterm    
      - RAILS_ENV=production
      - RACK_ENV=production           
    depends_on:
      - fcrepo
      - db
      - solr
    ports:
      - 3000:3000
    volumes:
      - ./hydra:/home/hydra
      - ./mfcs_export:/mfcs_export                     

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    container_name: fcrepo
    restart: on-failure    
    volumes:
      - ./fedora/data:/data:cached
    ports:
      - "8080:8080"  
      
  solr:
    image: solr:8.7
    container_name: solr
    restart: on-failure
    ports:
      - 8983:8983
    command:
      - sh
      - "-c"
      - "solr-precreate hydra_prod /opt/solr/server/configsets/hydraconf"
    volumes:
      - ./solr/data:/var/solr/data:cached
      - ./solr/conf:/opt/solr/server/configsets/hydraconf    

  db:
    image: mysql:5.7.27
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql:/var/lib/mysql

  conversion:
    build: 
      context: ./conversion/
      dockerfile: Dockerfile
    container_name: %%project_name%%_conversion
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./conversion/scripts:/convert/
      - ./conversion/control:/control/
      - ./mfcs_export:/mfcs_export
      - ./mnt:/mnt