source 'https://rubygems.org'

# Rails Dependencies
# =====================================================
gem 'rails', '~> 5.2.6'
gem 'bundler'
gem 'rake', '~> 12.3'
gem 'puma', '~> 4.3'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bootsnap', '>= 1.1.0', require: false

# OAI-PMH 
# =====================================================
gem 'blacklight_oai_provider'

# Automatic Import
# =====================================================
gem 'whenever', require: false

# Hydra Dependencies
# =====================================================
gem 'active-fedora'
gem 'active-triples'
gem 'blacklight'

gem 'hydra-head'
gem 'ldp'
gem 'nokogiri'
gem 'solrizer'

gem 'rsolr'
gem 'devise'
gem 'devise-guests', '~> 0.5'

gem 'rdf', '<= 3.1.13'

# Capistrano
# =====================================================
# gem 'capistrano-rails'

# DEVELOPMENT AND TESTS ONLY
# =====================================================
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rspec-rails'
  gem 'jettywrapper'
  gem 'listen'
  gem 'fcrepo_wrapper', '~> 0.4'
  gem 'solr_wrapper', '~> 2.0'
end

group :test do
  gem 'factory_bot_rails'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end